version: '3'

volumes:
  redis_data:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: alexsimonscreate/auto_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/

  celery-worker:
    image: alexsimonscreate/auto_celery-worker
    command:
      - celery
      - -A
      - config.celery
      - worker
      - -l
      - INFO
    depends_on:
      - backend
      - redis
    env_file:
      - .env

  celery-beat:
    image: alexsimonscreate/auto_celery-beat
    command:
      - celery
      - -A
      - config.celery
      - beat
      - -l
      - INFO
    depends_on:
      - backend
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  
  nginx:
    image: alexsimonscreate/auto_nginx
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - static:/staticfiles/